import { Metadata } from 'next';

export const meta: Metadata = {
  metadataBase: new URL('https://explorer.hiro.so/'),
  title: 'Base Explorer',
  description: 'Generated by Next.js',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
  },
  openGraph: {
    title: 'Base Explorer',
    type: 'website',
    siteName: 'explorer.hiro.so',
    description:
      'Explore transactions and accounts on the Base blockchain. Clone any contract and experiment in your browser with the Explorer sandbox.',
    images: '/StacksExplorer-OG.jpg',
  },
  twitter: {
    card: 'summary_large_image',
    site: '@stacks',
    creator: '@stacks',
    images: '/StacksExplorer-OG.jpg',
  },
  icons: {
    icon: {
      type: 'image/svg+xml',
      url: '/static/favicon.png',
    },
  },
};
